server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ayuside
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true  # 콘솔창에 sql 출력
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 서비스 계층으로 한정
    properties:
      hibernate:
        format_sql : true # 콘솔창에 sql 예쁘게 출력
        default_batch_fetch_size: 500 # 일대다 컬렉션 조회 시 성능 최적화
  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기 10MB로 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일의 크기의합 100MB로 제한

logging:
  level:
    org.hibernate.type: trace # 콘솔창에 조건에 바인딩되는 값 및 조회 결과 출력

kakao:
  client:
    id: feaf6c90472be43d7a2a4ff80f58b98f
    secret: 1JqrnkLOumyhaMPVjfz6Zrg2Q6XWUlb6

token:  #JWT 생성시 지정해야 하는 값들로 기준없이 넉넉하게 임의로 지정함
  secret: and0LXRva2VuLXNlY3JldA==            # 임의의 문자열
  access-token-expiration-time: 900000        # 단위 ms => 15분 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000   # 2주 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)